"use client";

import { useEffect, useMemo, useRef, useState } from "react";

import { EmptyState } from "@/components/shared/empty-state";
import { fmt } from "@/components/shared/format";
import { KpiCard } from "@/components/shared/kpi-card";
import { LoadingBlock } from "@/components/shared/LoadingBlock";
import { PageHeader } from "@/components/shared/page-header";
import { SectionCard } from "@/components/shared/section-card";
import { fitColor, readableInk } from "@/lib/treemap/fit-scale";

// ---------------------------------------------------------------------------
// Rules-engine test coverage: every policyengine-us Variable with rule logic
// (a formula or adds/subtracts), against the YAML policy tests that assert it
// in an output block. Direct coverage only — being executed as a dependency of
// a tested variable asserts nothing about a variable's own values.
// Data: public/model-coverage.json, regenerated by
// scripts/generate_model_coverage.py against a policyengine-us checkout.
// ---------------------------------------------------------------------------

interface CoverageNode {
  name: string;
  rules: number;
  tested: number;
  inputs: number;
  children?: CoverageNode[];
  untested?: string[];
}

interface CoverageData {
  source: { repo: string; version: string; commit: string };
  totals: { variables: number; rules: number; tested: number; inputs: number };
  tree: CoverageNode;
}

// --- tiny squarified treemap ------------------------------------------------

interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

interface Sized<T> {
  value: number;
  data: T;
}

type Placed<T> = Rect & { data: T };

function squarify<T>(items: Sized<T>[], rect: Rect): Placed<T>[] {
  const sorted = [...items].sort((a, b) => b.value - a.value);
  const total = sorted.reduce((s, i) => s + i.value, 0);
  if (!total) return [];
  const out: Placed<T>[] = [];
  let rest = { ...rect };
  let restValue = total;
  let row: Sized<T>[] = [];

  const worst = (r: Sized<T>[], side: number, area: number): number => {
    const sum = r.reduce((s, i) => s + i.value, 0) * (area / restValue);
    const max = Math.max(...r.map((i) => i.value)) * (area / restValue);
    const min = Math.min(...r.map((i) => i.value)) * (area / restValue);
    const s2 = sum * sum;
    return Math.max((side * side * max) / s2, s2 / (side * side * min));
  };

  const layoutRow = (r: Sized<T>[]) => {
    const area = rest.w * rest.h;
    const sum = r.reduce((s, i) => s + i.value, 0) * (area / restValue);
    const horizontal = rest.w >= rest.h;
    const side = horizontal ? rest.h : rest.w;
    const thickness = sum / side;
    let offset = 0;
    for (const item of r) {
      const len = (item.value * (area / restValue)) / thickness;
      out.push(
        horizontal
          ? { x: rest.x, y: rest.y + offset, w: thickness, h: len, data: item.data }
          : { x: rest.x + offset, y: rest.y, w: len, h: thickness, data: item.data },
      );
      offset += len;
    }
    restValue -= r.reduce((s, i) => s + i.value, 0);
    rest = horizontal
      ? { x: rest.x + thickness, y: rest.y, w: rest.w - thickness, h: rest.h }
      : { x: rest.x, y: rest.y + thickness, w: rest.w, h: rest.h - thickness };
  };

  for (const item of sorted) {
    const side = Math.min(rest.w, rest.h);
    const area = rest.w * rest.h;
    if (!row.length || worst([...row, item], side, area) <= worst(row, side, area)) {
      row.push(item);
    } else {
      layoutRow(row);
      row = [item];
    }
  }
  if (row.length) layoutRow(row);
  return out;
}

// --- coverage color ----------------------------------------------------------

// Same fit-scale ramp as the calibration map (teal-green → sage → amber →
// rose). Coverage share is mapped onto the scale's error axis so both maps
// share one visual language: green = healthy, warm = gaps.
const SHARE_TO_ERROR: [number, number][] = [
  [1.0, 0.0],
  [0.95, 0.03],
  [0.9, 0.06],
  [0.8, 0.1],
  [0.7, 0.2],
  [0.5, 0.4],
];

function coverageError(share: number): number {
  const s = Math.min(Math.max(share, 0), 1);
  if (s >= SHARE_TO_ERROR[0][0]) return SHARE_TO_ERROR[0][1];
  for (let i = 1; i < SHARE_TO_ERROR.length; i += 1) {
    const [hi, eHi] = SHARE_TO_ERROR[i - 1];
    const [lo, eLo] = SHARE_TO_ERROR[i];
    if (s >= lo) {
      const t = (hi - s) / (hi - lo);
      return eHi + (eLo - eHi) * t;
    }
  }
  return SHARE_TO_ERROR[SHARE_TO_ERROR.length - 1][1];
}

function coverageColor(share: number): string {
  return fitColor(coverageError(share));
}

function coverageTextColor(share: number): string {
  return readableInk(coverageError(share));
}

// Flatten one level: promote gov's children so groups are gov/irs, gov/states…
function topGroups(tree: CoverageNode): { label: string; node: CoverageNode }[] {
  const groups: { label: string; node: CoverageNode }[] = [];
  for (const child of tree.children ?? []) {
    if (child.name === "gov" && child.children?.length) {
      for (const g of child.children) {
        groups.push({ label: `gov/${g.name}`, node: g });
      }
    } else {
      groups.push({ label: child.name, node: child });
    }
  }
  return groups.filter((g) => g.node.rules > 0);
}

function worstPockets(tree: CoverageNode): { path: string; node: CoverageNode }[] {
  const pockets: { path: string; node: CoverageNode }[] = [];
  const walk = (n: CoverageNode, path: string) => {
    const children = n.children ?? [];
    for (const c of children) walk(c, `${path}/${c.name}`);
    if (!children.length && n.rules - n.tested > 0) {
      pockets.push({ path, node: n });
    }
  };
  walk(tree, tree.name);
  return pockets.sort((a, b) => (b.node.rules - b.node.tested) - (a.node.rules - a.node.tested)).slice(0, 15);
}

interface Selection {
  path: string;
  node: CoverageNode;
}

// Descendant serialization-leaves of a node, each carrying its untested names.
function untestedBreakdown(node: CoverageNode, path = ""): { path: string; node: CoverageNode }[] {
  const children = node.children ?? [];
  if (!children.length) {
    return node.rules - node.tested > 0 ? [{ path: path || node.name, node }] : [];
  }
  return children.flatMap((c) => untestedBreakdown(c, path ? `${path}/${c.name}` : c.name));
}

export function ModelCoverageView() {
  const [data, setData] = useState<CoverageData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<Selection | null>(null);
  const detailRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (selected) detailRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [selected]);

  useEffect(() => {
    fetch("/model-coverage.json")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then(setData)
      .catch((e) => setError(String(e)));
  }, []);

  const laid = useMemo(() => {
    if (!data) return [];
    const W = 1200;
    const H = 560;
    const groups = topGroups(data.tree);
    const placedGroups = squarify(
      groups.map((g) => ({ value: g.node.rules, data: g })),
      { x: 0, y: 0, w: W, h: H },
    );
    return placedGroups.map((pg) => {
      const pad = 3;
      const headerH = pg.h >= 56 && pg.w >= 80 ? 18 : 0;
      const inner = {
        x: pg.x + pad,
        y: pg.y + pad + headerH,
        w: Math.max(pg.w - pad * 2, 0),
        h: Math.max(pg.h - pad * 2 - headerH, 0),
      };
      const leaves = squarify(
        (pg.data.node.children ?? [{ ...pg.data.node, children: undefined }])
          .filter((c) => c.rules > 0)
          .map((c) => ({ value: c.rules, data: c })),
        inner,
      );
      return { group: pg, headerH, leaves };
    });
  }, [data]);

  if (error) return <EmptyState title="Coverage data unavailable" description={error} />;
  if (!data) return <LoadingBlock label="Loading model coverage…" />;

  const t = data.totals;
  return (
    <div className="flex flex-col gap-5">
      <PageHeader
        eyebrow="Populace · rules engine"
        title="Model test coverage"
        description={
          <>
            Every rule variable in{" "}
            <a
              className="underline decoration-dotted underline-offset-2"
              href="https://github.com/PolicyEngine/policyengine-us"
              target="_blank"
              rel="noreferrer"
            >
              policyengine-us
            </a>{" "}
            (v{data.source.version} @ {data.source.commit}) against the YAML policy tests
            that assert it. Direct coverage only: a variable exercised solely as a
            dependency of a tested variable counts as untested, because nothing asserts
            its own values — that is where unknown unknowns live.
          </>
        }
      />

      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <KpiCard label="Rule variables" value={fmt(t.rules, { digits: 0 })} hint={`+ ${fmt(t.inputs, { digits: 0 })} pure inputs`} />
        <KpiCard label="Directly tested" value={fmt(t.tested, { digits: 0 })} />
        <KpiCard label="Coverage" value={fmt(t.tested / t.rules, { pct: true, digits: 1 })} />
        <KpiCard label="Untested rules" value={fmt(t.rules - t.tested, { digits: 0 })} />
      </div>

      <SectionCard
        title="Coverage map"
        description="Tile area is the number of rule variables in that part of the tree; color is the share with a direct test — same scale as the calibration map: green means well tested, amber and rose are the gaps. Click a tile to see exactly which variables are missing tests."
      >
        <div className="overflow-x-auto">
          <svg viewBox="0 0 1200 560" className="min-w-[900px]" role="img" aria-label="model test coverage treemap">
            {laid.map(({ group, headerH, leaves }) => (
              <g key={group.data.label}>
                <rect
                  x={group.x + 1.5}
                  y={group.y + 1.5}
                  width={Math.max(group.w - 3, 0)}
                  height={Math.max(group.h - 3, 0)}
                  rx="6"
                  fill="#F8FAFC"
                  stroke="#CBD5E1"
                />
                {headerH > 0 && (
                  <text x={group.x + 8} y={group.y + 15} fontSize="10" fontWeight="700" fill="#334155">
                    {group.data.label}{" "}
                    <tspan fontWeight="400" fill="#64748B">
                      {Math.round((group.data.node.tested / group.data.node.rules) * 100)}%
                    </tspan>
                  </text>
                )}
                {leaves.map((leaf) => {
                  const share = leaf.data.rules ? leaf.data.tested / leaf.data.rules : 1;
                  if (leaf.w < 3 || leaf.h < 3) return null;
                  return (
                    <g key={`${group.data.label}/${leaf.data.name}`}>
                      <rect
                        x={leaf.x + 1}
                        y={leaf.y + 1}
                        width={Math.max(leaf.w - 2, 0)}
                        height={Math.max(leaf.h - 2, 0)}
                        rx={Math.min(4, Math.min(leaf.w, leaf.h) * 0.2)}
                        fill={coverageColor(share)}
                        fillOpacity={
                          selected && selected.path === `${group.data.label}/${leaf.data.name}`
                            ? 1
                            : 0.85
                        }
                        stroke={
                          selected && selected.path === `${group.data.label}/${leaf.data.name}`
                            ? "#0F172A"
                            : "none"
                        }
                        strokeWidth="1.5"
                        className="cursor-pointer"
                        onClick={() =>
                          setSelected({
                            path: `${group.data.label}/${leaf.data.name}`,
                            node: leaf.data,
                          })
                        }
                      >
                        <title>
                          {`${group.data.label}/${leaf.data.name} — ${leaf.data.tested}/${leaf.data.rules} rules tested (${Math.round(share * 100)}%) — click for details`}
                        </title>
                      </rect>
                      {leaf.w > 62 && leaf.h > 26 && (
                        <foreignObject x={leaf.x + 3} y={leaf.y + 2} width={leaf.w - 6} height={leaf.h - 4}>
                          <div
                            className="pointer-events-none overflow-hidden text-[9px] leading-tight"
                            style={{ color: coverageTextColor(share) }}
                          >
                            <div className="truncate font-semibold">{leaf.data.name}</div>
                            <div className="truncate opacity-90">
                              {leaf.data.tested}/{leaf.data.rules}
                            </div>
                          </div>
                        </foreignObject>
                      )}
                    </g>
                  );
                })}
              </g>
            ))}
          </svg>
        </div>
        <div className="mt-2 flex items-center gap-3 text-[11px] text-muted-foreground">
          <span>Coverage:</span>
          {[
            [1.0, "100%"],
            [0.95, "95%"],
            [0.9, "90%"],
            [0.8, "80%"],
            [0.7, "70%"],
            [0.5, "≤50%"],
          ].map(([v, label]) => (
            <span key={String(label)} className="inline-flex items-center gap-1">
              <span
                className="inline-block h-3 w-3 rounded-sm border border-border/60"
                style={{ background: coverageColor(v as number) }}
              />
              {label}
            </span>
          ))}
        </div>
      </SectionCard>

      {selected && (
        <div ref={detailRef}>
          <SectionCard
            title={selected.path}
            description={`${selected.node.tested}/${selected.node.rules} rules tested (${Math.round((selected.node.tested / Math.max(selected.node.rules, 1)) * 100)}%) · ${selected.node.rules - selected.node.tested} untested · ${selected.node.inputs} pure inputs`}
            actions={
              <button
                type="button"
                onClick={() => setSelected(null)}
                className="rounded border border-border px-2 py-1 text-xs text-muted-foreground hover:bg-muted/40"
              >
                Close ✕
              </button>
            }
          >
            {(() => {
              const breakdown = untestedBreakdown(selected.node);
              if (!breakdown.length) {
                return (
                  <div className="text-sm text-muted-foreground">
                    Every rule variable under this path has at least one direct test.
                  </div>
                );
              }
              return (
                <div className="flex flex-col gap-3">
                  {breakdown
                    .sort((a, b) => (b.node.rules - b.node.tested) - (a.node.rules - a.node.tested))
                    .map(({ path, node }) => (
                      <div key={path}>
                        <div className="flex items-baseline gap-2">
                          <span className="font-mono text-xs font-semibold text-foreground">
                            {selected.path}/{path}
                          </span>
                          <span className="text-xs text-muted-foreground">
                            {node.rules - node.tested} of {node.rules} untested
                          </span>
                        </div>
                        <div className="mt-0.5 flex flex-wrap gap-1">
                          {(node.untested ?? []).map((name) => (
                            <a
                              key={name}
                              href={`https://github.com/PolicyEngine/policyengine-us/search?q=${name}&type=code`}
                              target="_blank"
                              rel="noreferrer"
                              className="rounded border border-rose-200 bg-rose-50 px-1.5 py-0.5 font-mono text-[10px] text-rose-800 hover:bg-rose-100"
                            >
                              {name}
                            </a>
                          ))}
                        </div>
                      </div>
                    ))}
                </div>
              );
            })()}
          </SectionCard>
        </div>
      )}

      <SectionCard
        title="Largest untested pockets"
        description="Leaf directories with the most rule variables lacking any direct test — the concentrated unknown-unknowns."
        padded={false}
      >
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b border-border text-[11px] uppercase tracking-wider text-muted-foreground">
              <th className="px-3 py-2 font-semibold">Path</th>
              <th className="px-3 py-2 text-right font-semibold">Rules</th>
              <th className="px-3 py-2 text-right font-semibold">Tested</th>
              <th className="px-3 py-2 text-right font-semibold">Untested</th>
              <th className="px-3 py-2 font-semibold">Untested variables</th>
            </tr>
          </thead>
          <tbody>
            {worstPockets(data.tree).map(({ path, node }) => (
              <tr key={path} className="border-b border-border/60 align-top last:border-b-0">
                <td className="px-3 py-2 font-mono text-xs">{path.replace(/^variables\//, "")}</td>
                <td className="px-3 py-2 text-right tabular-nums">{node.rules}</td>
                <td className="px-3 py-2 text-right tabular-nums">{node.tested}</td>
                <td className="px-3 py-2 text-right font-medium tabular-nums text-rose-700">
                  {node.rules - node.tested}
                </td>
                <td className="max-w-xl px-3 py-2 font-mono text-[11px] leading-snug text-muted-foreground">
                  {(node.untested ?? []).slice(0, 8).join(", ")}
                  {(node.untested ?? []).length > 8 ? ", …" : ""}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </SectionCard>
    </div>
  );
}
