"use client";

import { useEffect, useMemo, useRef, useState } from "react";

import { EmptyState } from "@/components/shared/empty-state";
import { fmt } from "@/components/shared/format";
import { KpiCard } from "@/components/shared/kpi-card";
import { LoadingBlock } from "@/components/shared/LoadingBlock";
import { PageHeader } from "@/components/shared/page-header";
import { SectionCard } from "@/components/shared/section-card";
import { ToolbarSelect } from "@/components/shared/toolbar-select";
import { fitColor, readableInk } from "@/lib/treemap/fit-scale";

// ---------------------------------------------------------------------------
// Which policyengine-us rule variables the dashboard's own validation would
// notice breaking. Tiers: anchored (directly compared to an official number —
// a calibration target, reform score, or SOI backtest line), exercised
// (transitively feeds an anchored variable, via a static dependency scan), and
// unreached (invisible to every check — the unknown unknowns).
// Data: public/model-coverage.json, regenerated by
// scripts/generate_model_coverage.py against policyengine-us + populace
// checkouts and the live release artifact.
// ---------------------------------------------------------------------------

type Tier = "unreached" | "exercised" | "anchored";

interface CoverageNode {
  name: string;
  rules: number;
  anchored: number;
  exercised: number;
  inputs: number;
  children?: CoverageNode[];
  anchored_names?: string[];
  exercised_names?: string[];
  unreached_names?: string[];
}

interface CoverageData {
  source: { repo: string; version: string; commit: string };
  release_id?: string | null;
  anchor_counts: { calibration: number; reform: number; backtest: number };
  totals: {
    variables: number;
    rules: number;
    anchored: number;
    exercised: number;
    unreached: number;
    inputs: number;
  };
  tree: CoverageNode;
}

function reachedCount(n: CoverageNode): number {
  return n.anchored + n.exercised;
}

function unreachedIn(n: CoverageNode): number {
  return n.rules - reachedCount(n);
}

function tierCount(n: CoverageNode, tier: Tier): number {
  if (tier === "anchored") return n.anchored;
  if (tier === "exercised") return n.exercised;
  return unreachedIn(n);
}

function findNode(tree: CoverageNode, path: string[]): CoverageNode | null {
  let cur = tree;
  for (const part of path) {
    const next = (cur.children ?? []).find((c) => c.name === part);
    if (!next) return null;
    cur = next;
  }
  return cur;
}

// --- tiny squarified treemap ------------------------------------------------

interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

interface Sized<T> {
  value: number;
  data: T;
}

type Placed<T> = Rect & { data: T };

function squarify<T>(items: Sized<T>[], rect: Rect): Placed<T>[] {
  const sorted = [...items].sort((a, b) => b.value - a.value);
  const total = sorted.reduce((s, i) => s + i.value, 0);
  if (!total) return [];
  const out: Placed<T>[] = [];
  let rest = { ...rect };
  let restValue = total;
  let row: Sized<T>[] = [];

  const worst = (r: Sized<T>[], side: number, area: number): number => {
    const sum = r.reduce((s, i) => s + i.value, 0) * (area / restValue);
    const max = Math.max(...r.map((i) => i.value)) * (area / restValue);
    const min = Math.min(...r.map((i) => i.value)) * (area / restValue);
    const s2 = sum * sum;
    return Math.max((side * side * max) / s2, s2 / (side * side * min));
  };

  const layoutRow = (r: Sized<T>[]) => {
    const area = rest.w * rest.h;
    const sum = r.reduce((s, i) => s + i.value, 0) * (area / restValue);
    const horizontal = rest.w >= rest.h;
    const side = horizontal ? rest.h : rest.w;
    const thickness = sum / side;
    let offset = 0;
    for (const item of r) {
      const len = (item.value * (area / restValue)) / thickness;
      out.push(
        horizontal
          ? { x: rest.x, y: rest.y + offset, w: thickness, h: len, data: item.data }
          : { x: rest.x + offset, y: rest.y, w: len, h: thickness, data: item.data },
      );
      offset += len;
    }
    restValue -= r.reduce((s, i) => s + i.value, 0);
    rest = horizontal
      ? { x: rest.x + thickness, y: rest.y, w: rest.w - thickness, h: rest.h }
      : { x: rest.x, y: rest.y + thickness, w: rest.w, h: rest.h - thickness };
  };

  for (const item of sorted) {
    const side = Math.min(rest.w, rest.h);
    const area = rest.w * rest.h;
    if (!row.length || worst([...row, item], side, area) <= worst(row, side, area)) {
      row.push(item);
    } else {
      layoutRow(row);
      row = [item];
    }
  }
  if (row.length) layoutRow(row);
  return out;
}

// --- coverage color ----------------------------------------------------------

// Same fit-scale ramp as the calibration map (teal-green → sage → amber →
// rose). Reached share is mapped onto the scale's error axis so both maps
// share one visual language: green = validated, warm = blind spots.
const SHARE_TO_ERROR: [number, number][] = [
  [1.0, 0.0],
  [0.9, 0.03],
  [0.75, 0.06],
  [0.5, 0.1],
  [0.25, 0.2],
  [0.0, 0.4],
];

function coverageError(share: number): number {
  const s = Math.min(Math.max(share, 0), 1);
  if (s >= SHARE_TO_ERROR[0][0]) return SHARE_TO_ERROR[0][1];
  for (let i = 1; i < SHARE_TO_ERROR.length; i += 1) {
    const [hi, eHi] = SHARE_TO_ERROR[i - 1];
    const [lo, eLo] = SHARE_TO_ERROR[i];
    if (s >= lo) {
      const t = (hi - s) / (hi - lo);
      return eHi + (eLo - eHi) * t;
    }
  }
  return SHARE_TO_ERROR[SHARE_TO_ERROR.length - 1][1];
}

function coverageColor(share: number): string {
  return fitColor(coverageError(share));
}

function coverageTextColor(share: number): string {
  return readableInk(coverageError(share));
}

// --- grouping ----------------------------------------------------------------

interface Group {
  label: string;
  path: string[];
  node: CoverageNode;
  synthetic?: boolean;
}

// A directory can hold .py files directly AND subdirectories (390 do). The
// direct files are part of the node's rolled-up counts but belong to no child,
// so they get a synthetic "(direct)" tile to stay visible when drilling.
function directNode(n: CoverageNode): CoverageNode | null {
  if (!n.children?.length) return null;
  const a = n.anchored_names ?? [];
  const e = n.exercised_names ?? [];
  const u = n.unreached_names ?? [];
  const rules = a.length + e.length + u.length;
  if (!rules) return null;
  return {
    name: "(direct)",
    rules,
    anchored: a.length,
    exercised: e.length,
    inputs: 0,
    anchored_names: n.anchored_names,
    exercised_names: n.exercised_names,
    unreached_names: n.unreached_names,
  };
}

// At the tree root, promote gov's children so groups are gov/irs, gov/states…;
// when drilled into a cluster, groups are simply its children.
function groupsFor(node: CoverageNode, path: string[]): Group[] {
  const groups: Group[] = [];
  for (const child of node.children ?? []) {
    if (!path.length && child.name === "gov" && child.children?.length) {
      for (const g of child.children) {
        groups.push({ label: `gov/${g.name}`, path: ["gov", g.name], node: g });
      }
      const gd = directNode(child);
      if (gd) {
        groups.push({ label: "gov (direct)", path: ["gov", "(direct)"], node: gd, synthetic: true });
      }
    } else {
      groups.push({ label: child.name, path: [...path, child.name], node: child });
    }
  }
  const dn = directNode(node);
  if (dn) groups.push({ label: "(direct)", path: [...path, "(direct)"], node: dn, synthetic: true });
  return groups.filter((g) => g.node.rules > 0);
}

function collectTierNames(node: CoverageNode, tier: Tier): string[] {
  return [
    ...(node[`${tier}_names`] ?? []),
    ...(node.children ?? []).flatMap((c) => collectTierNames(c, tier)),
  ];
}

// Aggregate pockets at directory depth 4 (gov/states/mt/tax) so the table
// shows meaningful program-sized clusters, not fragmented deep leaves.
interface Pocket {
  path: string;
  rules: number;
  reached: number;
  unreached: string[];
}

function worstPockets(tree: CoverageNode): Pocket[] {
  const pockets: Pocket[] = [];
  const walk = (n: CoverageNode, path: string, depth: number) => {
    if (depth < 4 && n.children?.length) {
      for (const c of n.children) walk(c, `${path}/${c.name}`, depth + 1);
      // Files living directly in this directory belong to no child — surface
      // them as their own pocket so they are not silently skipped.
      const own = n.unreached_names ?? [];
      if (own.length) {
        const ownRules =
          (n.anchored_names?.length ?? 0) + (n.exercised_names?.length ?? 0) + own.length;
        pockets.push({ path, rules: ownRules, reached: ownRules - own.length, unreached: own });
      }
      return;
    }
    const unreached = collectTierNames(n, "unreached");
    if (unreached.length > 0) {
      pockets.push({ path, rules: n.rules, reached: reachedCount(n), unreached });
    }
  };
  walk(tree, tree.name, 0);
  return pockets.sort((a, b) => b.unreached.length - a.unreached.length).slice(0, 15);
}

interface Selection {
  path: string[];
  node: CoverageNode;
}

// Descendant directories of a node that hold names of the given tier.
function tierBreakdown(
  node: CoverageNode,
  tier: Tier,
  path = "",
): { path: string; names: string[] }[] {
  const own = node[`${tier}_names`] ?? [];
  const nested = (node.children ?? []).flatMap((c) =>
    tierBreakdown(c, tier, path ? `${path}/${c.name}` : c.name),
  );
  return own.length ? [{ path, names: own }, ...nested] : nested;
}

const TIER_META: Record<Tier, { label: string; chip: string; blurb: string }> = {
  unreached: {
    label: "Unreached",
    chip: "border-rose-200 bg-rose-50 text-rose-800 hover:bg-rose-100",
    blurb: "no dashboard check would move if these broke",
  },
  exercised: {
    label: "Exercised",
    chip: "border-amber-200 bg-amber-50 text-amber-800 hover:bg-amber-100",
    blurb: "feed an anchored number through the dependency graph",
  },
  anchored: {
    label: "Anchored",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-800 hover:bg-emerald-100",
    blurb: "directly compared to an official figure",
  },
};

export function ModelCoverageView({ initialPath = "" }: { initialPath?: string }) {
  const [data, setData] = useState<CoverageData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [root, setRoot] = useState<string[]>(
    initialPath ? initialPath.split("/").filter(Boolean) : [],
  );
  const [selected, setSelected] = useState<Selection | null>(null);
  const [tier, setTier] = useState<Tier>("unreached");
  const [chipSearch, setChipSearch] = useState("");
  const detailRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (selected) detailRef.current?.scrollIntoView({ behavior: "smooth", block: "center" });
  }, [selected]);

  useEffect(() => {
    fetch("/model-coverage.json")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then(setData)
      .catch((e) => setError(String(e)));
  }, []);

  // An unknown path (stale link, typo) falls back to the whole tree.
  const resolvedRoot = useMemo(
    () => (data && findNode(data.tree, root) ? root : []),
    [data, root],
  );
  const rootNode = useMemo(
    () => (data ? findNode(data.tree, resolvedRoot) : null),
    [data, resolvedRoot],
  );

  const laid = useMemo(() => {
    if (!rootNode) return [];
    const W = 1200;
    const H = 560;
    const groups = groupsFor(rootNode, resolvedRoot);
    const placedGroups = squarify(
      groups.map((g) => ({ value: g.node.rules, data: g })),
      { x: 0, y: 0, w: W, h: H },
    );
    return placedGroups.map((pg) => {
      const pad = 3;
      const headerH = pg.h >= 56 && pg.w >= 80 ? 18 : 0;
      const inner = {
        x: pg.x + pad,
        y: pg.y + pad + headerH,
        w: Math.max(pg.w - pad * 2, 0),
        h: Math.max(pg.h - pad * 2 - headerH, 0),
      };
      const grandchildren = (pg.data.node.children ?? []).filter((c) => c.rules > 0);
      const groupDirect = directNode(pg.data.node);
      const leaves = squarify(
        grandchildren.length
          ? [
              ...grandchildren.map((c) => ({
                value: c.rules,
                data: { node: c, path: [...pg.data.path, c.name] },
              })),
              ...(groupDirect
                ? [
                    {
                      value: groupDirect.rules,
                      data: { node: groupDirect, path: [...pg.data.path, "(direct)"] },
                    },
                  ]
                : []),
            ]
          : [{ value: pg.data.node.rules, data: { node: pg.data.node, path: pg.data.path } }],
        inner,
      );
      return { group: pg, headerH, leaves };
    });
  }, [rootNode, resolvedRoot]);

  if (error) return <EmptyState title="Coverage data unavailable" description={error} />;
  if (!data) return <LoadingBlock label="Loading model coverage…" />;

  const t = data.totals;
  const reached = t.anchored + t.exercised;
  const sectionOptions = [
    { value: "", label: "All sections" },
    ...groupsFor(data.tree, [])
      .filter((g) => !g.synthetic)
      .map((g) => ({ value: g.path.join("/"), label: g.label })),
  ];

  function drillTo(path: string[]) {
    setRoot(path);
    setSelected(null);
  }

  return (
    <div className="flex flex-col gap-5">
      <PageHeader
        eyebrow="Populace · rules engine"
        title="Model validation coverage"
        description={
          <>
            Which rule variables in{" "}
            <a
              className="underline decoration-dotted underline-offset-2"
              href="https://github.com/PolicyEngine/policyengine-us"
              target="_blank"
              rel="noreferrer"
            >
              policyengine-us
            </a>{" "}
            (v{data.source.version}) this dashboard&apos;s validation would notice
            breaking. <span className="font-medium text-foreground">Anchored</span> rules
            are directly compared to an official number — a calibration target (
            {fmt(data.anchor_counts.calibration, { digits: 0 })} variables), a JCT reform
            score ({fmt(data.anchor_counts.reform, { digits: 0 })}), or the IRS SOI
            backtest ({fmt(data.anchor_counts.backtest, { digits: 0 })}).{" "}
            <span className="font-medium text-foreground">Exercised</span> rules feed an
            anchored number, so a break moves a checked figure (static dependency scan —
            an approximation). Everything else is{" "}
            <span className="font-medium text-foreground">unreached</span>: it could be
            wrong and nothing here would move. Upstream unit tests are deliberately not
            counted.
          </>
        }
      />

      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <KpiCard
          label="Rule variables"
          value={fmt(t.rules, { digits: 0 })}
          hint={`+ ${fmt(t.inputs, { digits: 0 })} pure inputs`}
        />
        <KpiCard
          label="Anchored"
          value={fmt(t.anchored, { digits: 0 })}
          hint="directly checked vs official figures"
        />
        <KpiCard
          label="Reached"
          value={fmt(reached / t.rules, { pct: true, digits: 1 })}
          hint={`${fmt(t.exercised, { digits: 0 })} more feed a checked number`}
        />
        <KpiCard
          label="Unreached rules"
          value={fmt(t.unreached, { digits: 0 })}
          hint="invisible to every dashboard check"
        />
      </div>

      <SectionCard
        title="Validation reach map"
        description="Tile area is the number of rule variables in that part of the tree; color is the share reached by dashboard validation — same scale as the calibration map: green means watched, amber and rose are blind spots. Click a tile for its covered / uncovered variables; click a section header (or use the filter) to zoom in."
        actions={
          <ToolbarSelect
            label="Section"
            value={resolvedRoot.join("/")}
            onChange={(v) => drillTo(v ? v.split("/") : [])}
            options={sectionOptions}
          />
        }
      >
        {resolvedRoot.length > 0 && (
          <div className="mb-2 flex flex-wrap items-center gap-1 text-xs">
            <button
              type="button"
              onClick={() => drillTo([])}
              className="rounded border border-border px-1.5 py-0.5 text-muted-foreground hover:bg-muted/40 hover:text-foreground"
            >
              All
            </button>
            {resolvedRoot.map((part, i) => (
              <span key={`${part}-${i}`} className="flex items-center gap-1">
                <span className="text-muted-foreground">/</span>
                <button
                  type="button"
                  onClick={() => drillTo(resolvedRoot.slice(0, i + 1))}
                  className={`rounded border px-1.5 py-0.5 ${
                    i === resolvedRoot.length - 1
                      ? "border-primary/40 bg-primary/5 font-semibold text-foreground"
                      : "border-border text-muted-foreground hover:bg-muted/40 hover:text-foreground"
                  }`}
                >
                  {part}
                </button>
              </span>
            ))}
          </div>
        )}
        <div className="overflow-x-auto">
          <svg viewBox="0 0 1200 560" className="min-w-[900px]" role="img" aria-label="model validation coverage treemap">
            {laid.map(({ group, headerH, leaves }) => (
              <g key={group.data.label}>
                <rect
                  x={group.x + 1.5}
                  y={group.y + 1.5}
                  width={Math.max(group.w - 3, 0)}
                  height={Math.max(group.h - 3, 0)}
                  rx="6"
                  fill="#F8FAFC"
                  stroke="#CBD5E1"
                />
                {headerH > 0 && (
                  <text
                    x={group.x + 8}
                    y={group.y + 15}
                    fontSize="10"
                    fontWeight="700"
                    fill="#334155"
                    className={group.data.node.children?.length ? "cursor-pointer" : undefined}
                    onClick={() => group.data.node.children?.length && drillTo(group.data.path)}
                  >
                    {group.data.label}{" "}
                    <tspan fontWeight="400" fill="#64748B">
                      {Math.round((reachedCount(group.data.node) / group.data.node.rules) * 100)}%
                    </tspan>
                    {group.data.node.children?.length ? (
                      <tspan fontWeight="400" fill="#94A3B8">
                        {" "}
                        ↘
                      </tspan>
                    ) : null}
                    <title>Zoom into {group.data.label}</title>
                  </text>
                )}
                {leaves.map((leaf) => {
                  const n = leaf.data.node;
                  const leafPath = leaf.data.path.join("/");
                  const share = n.rules ? reachedCount(n) / n.rules : 1;
                  if (leaf.w < 3 || leaf.h < 3) return null;
                  const isSelected = selected?.path.join("/") === leafPath;
                  return (
                    <g key={leafPath}>
                      <rect
                        x={leaf.x + 1}
                        y={leaf.y + 1}
                        width={Math.max(leaf.w - 2, 0)}
                        height={Math.max(leaf.h - 2, 0)}
                        rx={Math.min(4, Math.min(leaf.w, leaf.h) * 0.2)}
                        fill={coverageColor(share)}
                        fillOpacity={isSelected ? 1 : 0.85}
                        stroke={isSelected ? "#0F172A" : "none"}
                        strokeWidth="1.5"
                        className="cursor-pointer transition-opacity hover:opacity-75"
                        onClick={() => setSelected({ path: leaf.data.path, node: n })}
                      >
                        <title>
                          {`${leafPath} — ${reachedCount(n)}/${n.rules} rules reached (${Math.round(share * 100)}%, ${n.anchored} anchored) — click for details`}
                        </title>
                      </rect>
                      {leaf.w > 62 && leaf.h > 26 && (
                        <foreignObject x={leaf.x + 3} y={leaf.y + 2} width={leaf.w - 6} height={leaf.h - 4}>
                          <div
                            className="pointer-events-none overflow-hidden text-[9px] leading-tight"
                            style={{ color: coverageTextColor(share) }}
                          >
                            <div className="truncate font-semibold">{n.name}</div>
                            <div className="truncate opacity-90">
                              {reachedCount(n)}/{n.rules}
                            </div>
                          </div>
                        </foreignObject>
                      )}
                    </g>
                  );
                })}
              </g>
            ))}
          </svg>
        </div>
        <div className="mt-2 flex items-center gap-3 text-[11px] text-muted-foreground">
          <span>Reached:</span>
          {[
            [1.0, "100%"],
            [0.9, "90%"],
            [0.75, "75%"],
            [0.5, "50%"],
            [0.25, "25%"],
            [0.0, "0%"],
          ].map(([v, label]) => (
            <span key={String(label)} className="inline-flex items-center gap-1">
              <span
                className="inline-block h-3 w-3 rounded-sm border border-border/60"
                style={{ background: coverageColor(v as number) }}
              />
              {label}
            </span>
          ))}
        </div>
      </SectionCard>

      {selected && (
        <div ref={detailRef}>
          <SectionCard
            title={selected.path.join("/")}
            description={`${reachedCount(selected.node)}/${selected.node.rules} rules reached (${Math.round((reachedCount(selected.node) / Math.max(selected.node.rules, 1)) * 100)}%) · ${selected.node.anchored} anchored · ${selected.node.exercised} exercised · ${unreachedIn(selected.node)} unreached · ${selected.node.inputs} pure inputs`}
            actions={
              <div className="flex items-center gap-2">
                {(selected.node.children?.length ?? 0) > 0 && (
                  <button
                    type="button"
                    onClick={() => drillTo(selected.path)}
                    className="rounded border border-primary/40 bg-primary/5 px-2 py-1 text-xs font-medium text-primary hover:bg-primary/10"
                  >
                    Expand cluster ↘
                  </button>
                )}
                <button
                  type="button"
                  onClick={() => setSelected(null)}
                  className="rounded border border-border px-2 py-1 text-xs text-muted-foreground hover:bg-muted/40"
                >
                  Close ✕
                </button>
              </div>
            }
          >
            <div className="mb-3 flex flex-wrap items-end gap-2">
              <div className="inline-flex items-center gap-1 rounded-full border border-border bg-muted/40 p-1">
                {(Object.keys(TIER_META) as Tier[]).map((k) => (
                  <button
                    key={k}
                    type="button"
                    onClick={() => setTier(k)}
                    className={`h-7 rounded-full px-3 text-xs font-medium transition-all ${
                      tier === k
                        ? "bg-white text-foreground shadow-sm ring-1 ring-black/5"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    {TIER_META[k].label} · {fmt(tierCount(selected.node, k), { digits: 0 })}
                  </button>
                ))}
              </div>
              <input
                type="search"
                value={chipSearch}
                placeholder="Filter variables…"
                onChange={(e) => setChipSearch(e.target.value)}
                className="h-8 w-48 rounded-md border border-border bg-white px-2.5 text-sm focus:border-primary/60 focus:outline-none"
              />
              <span className="pb-1 text-[11px] text-muted-foreground">
                {TIER_META[tier].blurb}
              </span>
            </div>
            {(() => {
              const q = chipSearch.trim().toLowerCase();
              const breakdown = tierBreakdown(selected.node, tier)
                .map(({ path, names }) => ({
                  path,
                  names: q ? names.filter((n) => n.includes(q)) : names,
                }))
                .filter(({ names }) => names.length > 0)
                .sort((a, b) => b.names.length - a.names.length);
              if (!breakdown.length) {
                return (
                  <div className="text-sm text-muted-foreground">
                    {q
                      ? `No ${TIER_META[tier].label.toLowerCase()} variables matching “${chipSearch}” here.`
                      : `No ${TIER_META[tier].label.toLowerCase()} variables under this path.`}
                  </div>
                );
              }
              return (
                <div className="flex flex-col gap-3">
                  {breakdown.map(({ path, names }) => (
                    <div key={path || "."}>
                      <div className="flex items-baseline gap-2">
                        <span className="font-mono text-xs font-semibold text-foreground">
                          {path ? `${selected.path.join("/")}/${path}` : selected.path.join("/")}
                        </span>
                        <span className="text-xs text-muted-foreground">
                          {names.length} {TIER_META[tier].label.toLowerCase()}
                        </span>
                      </div>
                      <div className="mt-0.5 flex flex-wrap gap-1">
                        {names.map((name) => (
                          <a
                            key={name}
                            href={`https://github.com/PolicyEngine/policyengine-us/search?q=${name}&type=code`}
                            target="_blank"
                            rel="noreferrer"
                            className={`rounded border px-1.5 py-0.5 font-mono text-[10px] ${TIER_META[tier].chip}`}
                          >
                            {name}
                          </a>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              );
            })()}
          </SectionCard>
        </div>
      )}

      <SectionCard
        title="Largest unreached pockets"
        description="Leaf directories with the most rule variables no dashboard check would catch — the concentrated unknown-unknowns."
        padded={false}
      >
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b border-border text-[11px] uppercase tracking-wider text-muted-foreground">
              <th className="px-3 py-2 font-semibold">Path</th>
              <th className="px-3 py-2 text-right font-semibold">Rules</th>
              <th className="px-3 py-2 text-right font-semibold">Reached</th>
              <th className="px-3 py-2 text-right font-semibold">Unreached</th>
              <th className="px-3 py-2 font-semibold">Unreached variables</th>
            </tr>
          </thead>
          <tbody>
            {worstPockets(data.tree).map(({ path, rules, reached: pocketReached, unreached }) => (
              <tr key={path} className="border-b border-border/60 align-top last:border-b-0">
                <td className="px-3 py-2 font-mono text-xs">{path.replace(/^variables\//, "")}</td>
                <td className="px-3 py-2 text-right tabular-nums">{rules}</td>
                <td className="px-3 py-2 text-right tabular-nums">{pocketReached}</td>
                <td className="px-3 py-2 text-right font-medium tabular-nums text-rose-700">
                  {unreached.length}
                </td>
                <td className="max-w-xl px-3 py-2 font-mono text-[11px] leading-snug text-muted-foreground">
                  {unreached.slice(0, 8).join(", ")}
                  {unreached.length > 8 ? ", …" : ""}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </SectionCard>
    </div>
  );
}
