"use client";

import { useEffect, useMemo, useRef, useState } from "react";

import { EmptyState } from "@/components/shared/empty-state";
import { fmt } from "@/components/shared/format";
import { KpiCard } from "@/components/shared/kpi-card";
import { LoadingBlock } from "@/components/shared/LoadingBlock";
import { PageHeader } from "@/components/shared/page-header";
import { SectionCard } from "@/components/shared/section-card";
import { ToolbarSelect } from "@/components/shared/toolbar-select";
import { withBasePath } from "@/lib/base-path";
import { fitColor, readableInk } from "@/lib/treemap/fit-scale";

// ---------------------------------------------------------------------------
// Which policyengine-us rule variables the dashboard's own validation would
// notice breaking. Tiers: anchored (directly compared to an official number —
// a calibration target, reform score, or SOI backtest line), exercised
// (transitively feeds an anchored variable, via a static dependency scan), and
// unreached (invisible to every check — the unknown unknowns).
// The map mirrors the release summary's calibration map: HTML button tiles
// with a pop-out cluster panel over the graph.
// Data: public/model-coverage.json, regenerated by
// scripts/generate_model_coverage.py against policyengine-us + populace
// checkouts and the live release artifact.
// ---------------------------------------------------------------------------

type Tier = "unreached" | "exercised" | "anchored";

interface CoverageNode {
  name: string;
  rules: number;
  anchored: number;
  exercised: number;
  inputs: number;
  children?: CoverageNode[];
  anchored_names?: string[];
  exercised_names?: string[];
  unreached_names?: string[];
}

interface CoverageData {
  source: { repo: string; version: string; commit: string };
  release_id?: string | null;
  anchor_counts: { calibration: number; reform: number; backtest: number };
  totals: {
    variables: number;
    rules: number;
    anchored: number;
    exercised: number;
    unreached: number;
    inputs: number;
  };
  tree: CoverageNode;
}

function reachedCount(n: CoverageNode): number {
  return n.anchored + n.exercised;
}

function unreachedIn(n: CoverageNode): number {
  return n.rules - reachedCount(n);
}

function tierCount(n: CoverageNode, tier: Tier): number {
  if (tier === "anchored") return n.anchored;
  if (tier === "exercised") return n.exercised;
  return unreachedIn(n);
}

function findNode(tree: CoverageNode, path: string[]): CoverageNode | null {
  let cur = tree;
  for (const part of path) {
    const next = (cur.children ?? []).find((c) => c.name === part);
    if (!next) return null;
    cur = next;
  }
  return cur;
}

// --- tiny squarified treemap ------------------------------------------------

interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

interface Sized<T> {
  value: number;
  data: T;
}

type Placed<T> = Rect & { data: T };

function squarify<T>(items: Sized<T>[], rect: Rect): Placed<T>[] {
  const sorted = [...items].sort((a, b) => b.value - a.value);
  const total = sorted.reduce((s, i) => s + i.value, 0);
  if (!total) return [];
  const out: Placed<T>[] = [];
  let rest = { ...rect };
  let restValue = total;
  let row: Sized<T>[] = [];

  const worst = (r: Sized<T>[], side: number, area: number): number => {
    const sum = r.reduce((s, i) => s + i.value, 0) * (area / restValue);
    const max = Math.max(...r.map((i) => i.value)) * (area / restValue);
    const min = Math.min(...r.map((i) => i.value)) * (area / restValue);
    const s2 = sum * sum;
    return Math.max((side * side * max) / s2, s2 / (side * side * min));
  };

  const layoutRow = (r: Sized<T>[]) => {
    const area = rest.w * rest.h;
    const sum = r.reduce((s, i) => s + i.value, 0) * (area / restValue);
    const horizontal = rest.w >= rest.h;
    const side = horizontal ? rest.h : rest.w;
    const thickness = sum / side;
    let offset = 0;
    for (const item of r) {
      const len = (item.value * (area / restValue)) / thickness;
      out.push(
        horizontal
          ? { x: rest.x, y: rest.y + offset, w: thickness, h: len, data: item.data }
          : { x: rest.x + offset, y: rest.y, w: len, h: thickness, data: item.data },
      );
      offset += len;
    }
    restValue -= r.reduce((s, i) => s + i.value, 0);
    rest = horizontal
      ? { x: rest.x + thickness, y: rest.y, w: rest.w - thickness, h: rest.h }
      : { x: rest.x, y: rest.y + thickness, w: rest.w, h: rest.h - thickness };
  };

  for (const item of sorted) {
    const side = Math.min(rest.w, rest.h);
    const area = rest.w * rest.h;
    if (!row.length || worst([...row, item], side, area) <= worst(row, side, area)) {
      row.push(item);
    } else {
      layoutRow(row);
      row = [item];
    }
  }
  if (row.length) layoutRow(row);
  return out;
}

// --- coverage color ----------------------------------------------------------

// Same fit-scale ramp as the calibration map (teal-green → sage → amber →
// rose). Reached share is mapped onto the scale's error axis so both maps
// share one visual language: green = validated, warm = blind spots.
const SHARE_TO_ERROR: [number, number][] = [
  [1.0, 0.0],
  [0.9, 0.03],
  [0.75, 0.06],
  [0.5, 0.1],
  [0.25, 0.2],
  [0.0, 0.4],
];

function coverageError(share: number): number {
  const s = Math.min(Math.max(share, 0), 1);
  if (s >= SHARE_TO_ERROR[0][0]) return SHARE_TO_ERROR[0][1];
  for (let i = 1; i < SHARE_TO_ERROR.length; i += 1) {
    const [hi, eHi] = SHARE_TO_ERROR[i - 1];
    const [lo, eLo] = SHARE_TO_ERROR[i];
    if (s >= lo) {
      const t = (hi - s) / (hi - lo);
      return eHi + (eLo - eHi) * t;
    }
  }
  return SHARE_TO_ERROR[SHARE_TO_ERROR.length - 1][1];
}

function coverageColor(share: number): string {
  return fitColor(coverageError(share));
}

function coverageTextColor(share: number): string {
  return readableInk(coverageError(share));
}

// --- grouping ----------------------------------------------------------------

interface Group {
  label: string;
  path: string[];
  node: CoverageNode;
  synthetic?: boolean;
}

// A directory can hold .py files directly AND subdirectories (390 do). The
// direct files are part of the node's rolled-up counts but belong to no child,
// so they get a synthetic "(direct)" tile to stay visible when drilling.
function directNode(n: CoverageNode): CoverageNode | null {
  if (!n.children?.length) return null;
  const a = n.anchored_names ?? [];
  const e = n.exercised_names ?? [];
  const u = n.unreached_names ?? [];
  const rules = a.length + e.length + u.length;
  if (!rules) return null;
  return {
    name: "(direct)",
    rules,
    anchored: a.length,
    exercised: e.length,
    inputs: 0,
    anchored_names: n.anchored_names,
    exercised_names: n.exercised_names,
    unreached_names: n.unreached_names,
  };
}

// At the tree root, promote gov's children so groups are gov/irs, gov/states…;
// when drilled into a cluster, groups are simply its children.
function groupsFor(node: CoverageNode, path: string[]): Group[] {
  const groups: Group[] = [];
  for (const child of node.children ?? []) {
    if (!path.length && child.name === "gov" && child.children?.length) {
      for (const g of child.children) {
        groups.push({ label: `gov/${g.name}`, path: ["gov", g.name], node: g });
      }
      const gd = directNode(child);
      if (gd) {
        groups.push({ label: "gov (direct)", path: ["gov", "(direct)"], node: gd, synthetic: true });
      }
    } else {
      groups.push({ label: child.name, path: [...path, child.name], node: child });
    }
  }
  const dn = directNode(node);
  if (dn) groups.push({ label: "(direct)", path: [...path, "(direct)"], node: dn, synthetic: true });
  return groups.filter((g) => g.node.rules > 0);
}

function collectTierNames(node: CoverageNode, tier: Tier): string[] {
  return [
    ...(node[`${tier}_names`] ?? []),
    ...(node.children ?? []).flatMap((c) => collectTierNames(c, tier)),
  ];
}

// Aggregate pockets at directory depth 4 (gov/states/mt/tax) so the table
// shows meaningful program-sized clusters, not fragmented deep leaves.
interface Pocket {
  path: string;
  rules: number;
  reached: number;
  unreached: string[];
}

function worstPockets(tree: CoverageNode): Pocket[] {
  const pockets: Pocket[] = [];
  const walk = (n: CoverageNode, path: string, depth: number) => {
    if (depth < 4 && n.children?.length) {
      for (const c of n.children) walk(c, `${path}/${c.name}`, depth + 1);
      // Files living directly in this directory belong to no child — surface
      // them as their own pocket so they are not silently skipped.
      const own = n.unreached_names ?? [];
      if (own.length) {
        const ownRules =
          (n.anchored_names?.length ?? 0) + (n.exercised_names?.length ?? 0) + own.length;
        pockets.push({ path, rules: ownRules, reached: ownRules - own.length, unreached: own });
      }
      return;
    }
    const unreached = collectTierNames(n, "unreached");
    if (unreached.length > 0) {
      pockets.push({ path, rules: n.rules, reached: reachedCount(n), unreached });
    }
  };
  walk(tree, tree.name, 0);
  return pockets.sort((a, b) => b.unreached.length - a.unreached.length).slice(0, 15);
}

interface Selection {
  path: string[];
  node: CoverageNode;
}

// Descendant directories of a node that hold names of the given tier.
function tierBreakdown(
  node: CoverageNode,
  tier: Tier,
  path = "",
): { path: string; names: string[] }[] {
  const own = node[`${tier}_names`] ?? [];
  const nested = (node.children ?? []).flatMap((c) =>
    tierBreakdown(c, tier, path ? `${path}/${c.name}` : c.name),
  );
  return own.length ? [{ path, names: own }, ...nested] : nested;
}

const TIER_META: Record<Tier, { label: string; chip: string; blurb: string }> = {
  unreached: {
    label: "Unreached",
    chip: "border-rose-200 bg-rose-50 text-rose-800 hover:bg-rose-100",
    blurb: "no dashboard check would move if these broke",
  },
  exercised: {
    label: "Exercised",
    chip: "border-amber-200 bg-amber-50 text-amber-800 hover:bg-amber-100",
    blurb: "feed an anchored number through the dependency graph",
  },
  anchored: {
    label: "Anchored",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-800 hover:bg-emerald-100",
    blurb: "directly compared to an official figure",
  },
};

// --- cluster pop-out (same mechanism as the release summary map) -------------

function ClusterPopup({
  selection,
  atRoot,
  onExpand,
  onClose,
}: {
  selection: Selection;
  atRoot: boolean;
  onExpand: () => void;
  onClose: () => void;
}) {
  const [tier, setTier] = useState<Tier>("unreached");
  const [search, setSearch] = useState("");
  const node = selection.node;
  const share = node.rules ? reachedCount(node) / node.rules : 1;

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const q = search.trim().toLowerCase();
  const breakdown = tierBreakdown(node, tier)
    .map(({ path, names }) => ({
      path,
      names: q ? names.filter((n) => n.includes(q)) : names,
    }))
    .filter(({ names }) => names.length > 0)
    .sort((a, b) => b.names.length - a.names.length);

  return (
    <div className="flex h-full flex-col overflow-hidden rounded-xl border border-border bg-white shadow-2xl ring-1 ring-black/5">
      {/* header */}
      <div className="flex flex-wrap items-start justify-between gap-3 border-b border-border bg-muted/20 px-4 py-3">
        <div className="flex min-w-0 items-start gap-2.5">
          <span
            className="mt-1 h-3.5 w-3.5 shrink-0 rounded-full ring-1 ring-black/10"
            style={{ background: coverageColor(share) }}
          />
          <div className="min-w-0">
            <div className="font-mono text-sm font-semibold leading-tight text-foreground">
              {selection.path.join("/")}
            </div>
            <div className="mt-0.5 text-xs text-muted-foreground">
              {reachedCount(node)}/{node.rules} rules reached ({Math.round(share * 100)}%) ·{" "}
              {node.inputs} pure inputs
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {(node.children?.length ?? 0) > 0 && !atRoot && (
            <button
              type="button"
              onClick={onExpand}
              className="rounded border border-primary/40 bg-primary/5 px-2 py-1 text-xs font-medium text-primary hover:bg-primary/10"
            >
              Expand cluster ↘
            </button>
          )}
          <button
            type="button"
            onClick={onClose}
            aria-label="Close cluster details"
            className="grid h-7 w-7 place-items-center rounded-md border border-border text-muted-foreground hover:bg-muted/60 hover:text-foreground"
          >
            ✕
          </button>
        </div>
      </div>

      {/* filters */}
      <div className="flex flex-wrap items-center gap-2 border-b border-border bg-white px-4 py-2.5">
        <div className="inline-flex items-center gap-1 rounded-full border border-border bg-muted/40 p-1">
          {(Object.keys(TIER_META) as Tier[]).map((k) => (
            <button
              key={k}
              type="button"
              onClick={() => setTier(k)}
              className={`h-7 rounded-full px-3 text-xs font-medium transition-all ${
                tier === k
                  ? "bg-white text-foreground shadow-sm ring-1 ring-black/5"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              {TIER_META[k].label} · {fmt(tierCount(node, k), { digits: 0 })}
            </button>
          ))}
        </div>
        <input
          type="search"
          value={search}
          placeholder="Filter variables…"
          onChange={(e) => setSearch(e.target.value)}
          className="h-8 w-44 rounded-md border border-border bg-white px-2.5 text-sm focus:border-primary/60 focus:outline-none"
        />
        <span className="text-[11px] text-muted-foreground">{TIER_META[tier].blurb}</span>
      </div>

      {/* body */}
      <div className="min-h-0 flex-1 overflow-y-auto px-4 py-3">
        {!breakdown.length ? (
          <div className="py-8 text-center text-sm text-muted-foreground">
            {q
              ? `No ${TIER_META[tier].label.toLowerCase()} variables matching “${search}” here.`
              : `No ${TIER_META[tier].label.toLowerCase()} variables under this path.`}
          </div>
        ) : (
          <div className="flex flex-col gap-3">
            {breakdown.map(({ path, names }) => (
              <div key={path || "."}>
                <div className="flex items-baseline gap-2">
                  <span className="font-mono text-xs font-semibold text-foreground">
                    {path ? `${selection.path.join("/")}/${path}` : selection.path.join("/")}
                  </span>
                  <span className="text-xs text-muted-foreground">
                    {names.length} {TIER_META[tier].label.toLowerCase()}
                  </span>
                </div>
                <div className="mt-0.5 flex flex-wrap gap-1">
                  {names.map((name) => (
                    <a
                      key={name}
                      href={`https://github.com/PolicyEngine/policyengine-us/search?q=${name}&type=code`}
                      target="_blank"
                      rel="noreferrer"
                      className={`rounded border px-1.5 py-0.5 font-mono text-[10px] ${TIER_META[tier].chip}`}
                    >
                      {name}
                    </a>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// --- main view ----------------------------------------------------------------

export function ModelCoverageView({ initialPath = "" }: { initialPath?: string }) {
  const [data, setData] = useState<CoverageData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [root, setRoot] = useState<string[]>(
    initialPath ? initialPath.split("/").filter(Boolean) : [],
  );
  const [selected, setSelected] = useState<Selection | null>(null);
  const [hovered, setHovered] = useState<string | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [width, setWidth] = useState(1100);

  useEffect(() => {
    fetch(withBasePath("/model-coverage.json"))
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then(setData)
      .catch((e) => setError(String(e)));
  }, []);

  // Depends on `data`: the container only renders once loading finishes, so
  // observing on first mount would attach to nothing and the map would stay
  // at its fallback width.
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    setWidth(Math.round(el.getBoundingClientRect().width));
    const observer = new ResizeObserver((entries) => {
      const w = entries[0]?.contentRect.width;
      if (w) setWidth(Math.round(w));
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, [data]);

  // An unknown path (stale link, typo) falls back to the whole tree.
  const resolvedRoot = useMemo(
    () => (data && findNode(data.tree, root) ? root : []),
    [data, root],
  );
  const rootNode = useMemo(
    () => (data ? findNode(data.tree, resolvedRoot) : null),
    [data, resolvedRoot],
  );

  const height = Math.round(Math.min(Math.max(width * 0.52, 420), 620));

  const laid = useMemo(() => {
    if (!rootNode) return [];
    const groups = groupsFor(rootNode, resolvedRoot);
    const placedGroups = squarify(
      groups.map((g) => ({ value: g.node.rules, data: g })),
      { x: 0, y: 0, w: width, h: height },
    );
    return placedGroups.map((pg) => {
      const pad = 3;
      const headerH = pg.h >= 56 && pg.w >= 80 ? 18 : 0;
      const inner = {
        x: pg.x + pad,
        y: pg.y + pad + headerH,
        w: Math.max(pg.w - pad * 2, 0),
        h: Math.max(pg.h - pad * 2 - headerH, 0),
      };
      const grandchildren = (pg.data.node.children ?? []).filter((c) => c.rules > 0);
      const groupDirect = directNode(pg.data.node);
      const leaves = squarify(
        grandchildren.length
          ? [
              ...grandchildren.map((c) => ({
                value: c.rules,
                data: { node: c, path: [...pg.data.path, c.name] },
              })),
              ...(groupDirect
                ? [
                    {
                      value: groupDirect.rules,
                      data: { node: groupDirect, path: [...pg.data.path, "(direct)"] },
                    },
                  ]
                : []),
            ]
          : [{ value: pg.data.node.rules, data: { node: pg.data.node, path: pg.data.path } }],
        inner,
      );
      return { group: pg, headerH, leaves };
    });
  }, [rootNode, resolvedRoot, width, height]);

  if (error) return <EmptyState title="Coverage data unavailable" description={error} />;
  if (!data) return <LoadingBlock label="Loading model coverage…" />;

  const t = data.totals;
  const reached = t.anchored + t.exercised;
  const sectionOptions = [
    { value: "", label: "All sections" },
    ...groupsFor(data.tree, [])
      .filter((g) => !g.synthetic)
      .map((g) => ({ value: g.path.join("/"), label: g.label })),
  ];

  function drillTo(path: string[]) {
    setRoot(path);
    setSelected(null);
  }

  return (
    <div className="flex flex-col gap-5">
      <PageHeader
        eyebrow="Populace · rules engine"
        title="Validation reach"
        description={
          <>
            Which rule variables in{" "}
            <a
              className="underline decoration-dotted underline-offset-2"
              href="https://github.com/PolicyEngine/policyengine-us"
              target="_blank"
              rel="noreferrer"
            >
              policyengine-us
            </a>{" "}
            (v{data.source.version}) this dashboard&apos;s validation would notice
            breaking. <span className="font-medium text-foreground">Anchored</span> rules
            are directly compared to an official number — a calibration target (
            {fmt(data.anchor_counts.calibration, { digits: 0 })} variables), a JCT reform
            score ({fmt(data.anchor_counts.reform, { digits: 0 })}), or the IRS SOI
            backtest ({fmt(data.anchor_counts.backtest, { digits: 0 })}).{" "}
            <span className="font-medium text-foreground">Exercised</span> rules feed an
            anchored number, so a break moves a checked figure (static dependency scan —
            an approximation). Everything else is{" "}
            <span className="font-medium text-foreground">unreached</span>: it could be
            wrong and nothing here would move. Upstream unit tests are deliberately not
            counted.
          </>
        }
      />

      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <KpiCard
          label="Rule variables"
          value={fmt(t.rules, { digits: 0 })}
          hint={`+ ${fmt(t.inputs, { digits: 0 })} pure inputs`}
        />
        <KpiCard
          label="Anchored"
          value={fmt(t.anchored, { digits: 0 })}
          hint="directly checked vs official figures"
        />
        <KpiCard
          label="Reached"
          value={fmt(reached / t.rules, { pct: true, digits: 1 })}
          hint={`${fmt(t.exercised, { digits: 0 })} more feed a checked number`}
        />
        <KpiCard
          label="Unreached rules"
          value={fmt(t.unreached, { digits: 0 })}
          hint="invisible to every dashboard check"
        />
      </div>

      <SectionCard
        title="Validation reach map"
        description="Tile area is the number of rule variables in that part of the tree; color is the share reached by dashboard validation — same scale as the calibration map: green means watched, amber and rose are blind spots. Click a tile to pop out its covered / uncovered variables; expand from there (or click a section header) to zoom in."
        actions={
          <ToolbarSelect
            label="Section"
            value={resolvedRoot.join("/")}
            onChange={(v) => drillTo(v ? v.split("/") : [])}
            options={sectionOptions}
          />
        }
      >
        {resolvedRoot.length > 0 && (
          <div className="mb-2 flex flex-wrap items-center gap-1 text-xs">
            <button
              type="button"
              onClick={() => drillTo([])}
              className="rounded border border-border px-1.5 py-0.5 text-muted-foreground hover:bg-muted/40 hover:text-foreground"
            >
              All
            </button>
            {resolvedRoot.map((part, i) => (
              <span key={`${part}-${i}`} className="flex items-center gap-1">
                <span className="text-muted-foreground">/</span>
                <button
                  type="button"
                  onClick={() => drillTo(resolvedRoot.slice(0, i + 1))}
                  className={`rounded border px-1.5 py-0.5 ${
                    i === resolvedRoot.length - 1
                      ? "border-primary/40 bg-primary/5 font-semibold text-foreground"
                      : "border-border text-muted-foreground hover:bg-muted/40 hover:text-foreground"
                  }`}
                >
                  {part}
                </button>
              </span>
            ))}
          </div>
        )}

        <div ref={containerRef} className="relative w-full" style={{ height }}>
          {laid.map(({ group, headerH, leaves }) => (
            <div key={group.data.label}>
              <div
                className="absolute rounded-md border border-border/80 bg-slate-50"
                style={{
                  left: group.x + 1.5,
                  top: group.y + 1.5,
                  width: Math.max(group.w - 3, 0),
                  height: Math.max(group.h - 3, 0),
                }}
              />
              {headerH > 0 && (
                <button
                  type="button"
                  onClick={() =>
                    group.data.node.children?.length
                      ? drillTo(group.data.path)
                      : setSelected({ path: group.data.path, node: group.data.node })
                  }
                  title={
                    group.data.node.children?.length
                      ? `Zoom into ${group.data.label}`
                      : group.data.label
                  }
                  className="absolute flex items-baseline gap-1.5 overflow-hidden text-left"
                  style={{ left: group.x + 8, top: group.y + 3, width: group.w - 12, height: headerH }}
                >
                  <span className="truncate text-[11px] font-semibold tracking-tight text-foreground hover:underline">
                    {group.data.label}
                  </span>
                  <span className="shrink-0 font-mono text-[10px] text-muted-foreground">
                    {Math.round((reachedCount(group.data.node) / group.data.node.rules) * 100)}%
                    {group.data.node.children?.length ? " ↘" : ""}
                  </span>
                </button>
              )}
              {leaves.map((leaf) => {
                const n = leaf.data.node;
                const leafPath = leaf.data.path.join("/");
                const share = n.rules ? reachedCount(n) / n.rules : 1;
                const w = Math.max(leaf.w - 2, 0);
                const h = Math.max(leaf.h - 2, 0);
                if (w < 4 || h < 4) return null;
                const isSelected = selected?.path.join("/") === leafPath;
                const isHover = hovered === leafPath;
                const showText = w >= 46 && h >= 24;
                return (
                  <button
                    type="button"
                    key={leafPath}
                    aria-label={`${leafPath}, ${reachedCount(n)} of ${n.rules} rules reached`}
                    aria-pressed={isSelected}
                    title={`${leafPath} — ${reachedCount(n)}/${n.rules} rules reached (${Math.round(share * 100)}%) — click for details`}
                    onClick={() => setSelected({ path: leaf.data.path, node: n })}
                    onMouseEnter={() => setHovered(leafPath)}
                    onMouseLeave={() => setHovered(null)}
                    className="group absolute flex flex-col overflow-hidden px-1.5 py-1 text-left outline-none transition-[transform,box-shadow,opacity] duration-150 focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-1"
                    style={{
                      left: leaf.x + 1,
                      top: leaf.y + 1,
                      width: w,
                      height: h,
                      borderRadius: Math.max(1.5, Math.min(5, Math.min(w, h) * 0.25)),
                      background: coverageColor(share),
                      color: coverageTextColor(share),
                      opacity: selected && !isSelected ? 0.65 : isHover ? 1 : 0.92,
                      zIndex: isSelected ? 11 : isHover ? 10 : 1,
                      transform: isHover || isSelected ? "scale(1.015)" : "scale(1)",
                      boxShadow: isSelected
                        ? "0 0 0 2px #ffffff, 0 0 0 4px #319795, 0 8px 22px -6px rgba(15,23,42,0.35)"
                        : isHover
                          ? "0 6px 20px -4px rgba(15,23,42,0.3), inset 0 0 0 1px rgba(255,255,255,0.25)"
                          : "inset 0 0 0 1px rgba(255,255,255,0.08)",
                    }}
                  >
                    {showText && (
                      <>
                        <span className="truncate text-[10px] font-semibold leading-tight">
                          {n.name}
                        </span>
                        <span className="truncate text-[9px] leading-tight opacity-85">
                          {reachedCount(n)}/{n.rules}
                        </span>
                      </>
                    )}
                  </button>
                );
              })}
            </div>
          ))}

          {/* cluster detail pops out over the graph, like the calibration map */}
          {selected && (
            <div className="absolute inset-0 z-30">
              <style>{`@keyframes scrimIn{from{opacity:0}to{opacity:1}}@keyframes popIn{from{opacity:0;transform:scale(0.97)}to{opacity:1;transform:none}}`}</style>
              <button
                type="button"
                aria-label="Close cluster details"
                onClick={() => setSelected(null)}
                className="absolute inset-0 cursor-default bg-slate-900/20 backdrop-blur-[2px] motion-safe:animate-[scrimIn_140ms_ease-out]"
              />
              <div className="absolute inset-2 motion-safe:animate-[popIn_180ms_cubic-bezier(0.16,1,0.3,1)] sm:inset-3">
                <ClusterPopup
                  key={selected.path.join("/")}
                  selection={selected}
                  atRoot={selected.path.join("/") === resolvedRoot.join("/")}
                  onExpand={() => drillTo(selected.path)}
                  onClose={() => setSelected(null)}
                />
              </div>
            </div>
          )}
        </div>

        <div className="mt-2 flex items-center gap-3 text-[11px] text-muted-foreground">
          <span>Reached:</span>
          {[
            [1.0, "100%"],
            [0.9, "90%"],
            [0.75, "75%"],
            [0.5, "50%"],
            [0.25, "25%"],
            [0.0, "0%"],
          ].map(([v, label]) => (
            <span key={String(label)} className="inline-flex items-center gap-1">
              <span
                className="inline-block h-3 w-3 rounded-sm border border-border/60"
                style={{ background: coverageColor(v as number) }}
              />
              {label}
            </span>
          ))}
        </div>
      </SectionCard>

      <SectionCard
        title="Largest unreached pockets"
        description="Leaf directories with the most rule variables no dashboard check would catch — the concentrated unknown-unknowns."
        padded={false}
      >
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b border-border text-[11px] uppercase tracking-wider text-muted-foreground">
              <th className="px-3 py-2 font-semibold">Path</th>
              <th className="px-3 py-2 text-right font-semibold">Rules</th>
              <th className="px-3 py-2 text-right font-semibold">Reached</th>
              <th className="px-3 py-2 text-right font-semibold">Unreached</th>
              <th className="px-3 py-2 font-semibold">Unreached variables</th>
            </tr>
          </thead>
          <tbody>
            {worstPockets(data.tree).map(({ path, rules, reached: pocketReached, unreached }) => (
              <tr key={path} className="border-b border-border/60 align-top last:border-b-0">
                <td className="px-3 py-2 font-mono text-xs">{path.replace(/^variables\//, "")}</td>
                <td className="px-3 py-2 text-right tabular-nums">{rules}</td>
                <td className="px-3 py-2 text-right tabular-nums">{pocketReached}</td>
                <td className="px-3 py-2 text-right font-medium tabular-nums text-rose-700">
                  {unreached.length}
                </td>
                <td className="max-w-xl px-3 py-2 font-mono text-[11px] leading-snug text-muted-foreground">
                  {unreached.slice(0, 8).join(", ")}
                  {unreached.length > 8 ? ", …" : ""}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </SectionCard>
    </div>
  );
}
