export const PUBLISHED_RELEASE_CACHE_SECONDS = 6 * 60 * 60;
export const PUBLISHED_RELEASE_STALE_TIME_MS = PUBLISHED_RELEASE_CACHE_SECONDS * 1000;
export const LATEST_RELEASE_STALE_TIME_MS = 60 * 1000;
